# Number of states / Number of inputs
numStates: 3
numInputs: 2

# Cost matrices
Q: [100, 0, 0, 0, 100, 0, 0, 0, 0]
R: [1, 0, 0, 0.1]

# Hardware parameters
lr: 0.15
lf: 0.15

#Box constraints on states
x_min: 0
x_max: 5
y_min: -2
y_max: 2

# Box constraints on input, A*u <= B
v_max: 0.4
v_min: 0
steer_min: -1
steer_max: 1

loop_rate: 12
